# Site settings
title: Thomas Lamb 
email: contact@thomaslamb.dev
url: https://github.com/ThomasLambProgramming
description: "Junior game programmer who is currently studying at the Academy of Interactive Entertainment, looking to become an AI game programmer"
keywords: "your keywords, separated by commas"
skills: "Unity Developer, C# programmer"
meta_author: Lamb Thomas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Thomas Lamb	
  location: Sydney
  social: Linkedin, Github
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: linkedin
    url: https://www.linkedin.com/in/thomaslambprogramming/
  - title: github
    url: https://github.com/ThomasLambProgramming

# Credits content
credits: 'Thank you very much for looking at my portfolio.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
